"""AI Analyst: evidence-grounded analysis of a Market Pulse snapshot.

Sits on top of Market Pulse and performs no discovery of its own. It resolves
no locations, identifies no merchants, matches no products and makes no
provider search request, so it can never spend a SerpApi credit. It writes
nothing.

Why the facts are not generated by the model
--------------------------------------------
"Never invent facts" cannot be guaranteed by asking a language model nicely.
So the responsibility is split, and the split is the architecture:

* **Code produces the facts.** Every ``Observation`` below is computed from the
  snapshot by a Python function and carries an ``EvidenceRef`` back to the
  records it came from. A model is never asked to produce one.
* **The model produces only prose.** It receives the already-computed facts --
  never the raw data to interpret -- and writes a summary of them.
* **The prose is then validated.** A summary asserting a banned conclusion, or
  citing a number that does not appear in the computed facts, is withheld and
  the reason reported. It is never shown.

The consequence is that with no provider configured the analyst still returns
its full factual analysis; only the narrative is absent. That is a better
answer than nothing, and it is not "fake analysis" because no model was
involved in producing it.

Nothing here concludes. There is no winner, no market leader, no growth, no
prediction and no score -- each would be an inference the evidence does not
support.
"""
import json
import re
from datetime import datetime, timezone
from typing import List, Optional, Tuple

from sqlalchemy.orm import Session

from app.schemas.analyst import AnalystResponse, EvidenceRef, Observation
from app.schemas.pulse import MarketPulseResponse
from app.services.ai_provider import (
    AIProvider, AIProviderError, AIProviderNotConfigured, get_ai_provider,
)
from app.services.pulse_service import MarketPulseService

OBSERVATION = "observation"
LIMITATION = "limitation"
INSUFFICIENT = "insufficient_evidence"

# Claims the analyst may never make, in any wording. Each is an inference the
# observation history cannot support: a ranking, a prediction, or a judgement
# about a business's fate. Matched as whole words against a validated summary.
BANNED_CLAIMS = (
    "market leader", "leading competitor", "dominant", "dominates", "dominate",
    "winner", "winning", "loser", "losing", "outperform", "outperforms",
    "best competitor", "worst competitor", "top competitor", "strongest competitor",
    "weakest competitor", "market share", "growing", "growth", "shrinking",
    "declining market", "will increase", "will decrease", "will grow", "will fall",
    "expected to", "likely to", "we predict", "forecast", "projection",
    "demand is high", "demand is low", "high demand", "low demand",
    "customers prefer", "consumers prefer", "customer preference",
    "went out of business", "going out of business", "closed down",
    "has disappeared", "disappeared from", "no longer operates",
    "we recommend", "you should", "it is advisable", "opportunity to capture",
    # Paraphrases of the same conclusions. Stems, so "leads"/"leading" etc.
    # are covered by the suffix rule below.
    "leader", "leads the market", "leading the market", "strongest", "weakest",
    "underperform", "most successful", "most popular", "recommend", "should",
    "advise", "expanding", "booming", "surging", "demand", "confidence score",
    "score of",
)

# Matched as a stem with any suffix, so "outperform" also catches
# "outperforming" and "outperforms". A word boundary alone let those through.
_BANNED_PATTERNS = [(claim, re.compile(r"\b" + re.escape(claim) + r"\w*", re.IGNORECASE))
                    for claim in BANNED_CLAIMS]

_NUMBER_RE = re.compile(r"\d+(?:\.\d+)?")

SYSTEM_PROMPT = (
    "You summarise market observation data for an analyst. You will be given a "
    "list of statements that were computed from recorded observations. "
    "Rules you must follow exactly:\n"
    "1. Use only the statements provided. Do not add facts, figures, names or "
    "context from anywhere else.\n"
    "2. Do not draw conclusions. Never say a business is a market leader, is "
    "winning, losing, dominant, growing or declining. Never predict anything.\n"
    "3. Never state or imply that a business has closed or left the market.\n"
    "4. Where a statement says evidence is insufficient, say so plainly.\n"
    "5. Use only numbers that appear in the provided statements.\n"
    "6. Write at most 150 words of plain prose. No headings, no bullet points, "
    "no scores."
)


def _ref(section: str, detail: Optional[str] = None, record_ids=None,
         merchant_ids=None, count: Optional[int] = None) -> EvidenceRef:
    return EvidenceRef(section=section, detail=detail,
                       record_ids=list(record_ids or []),
                       merchant_ids=list(merchant_ids or []), count=count)


def _plural(count: int, singular: str, plural: Optional[str] = None) -> str:
    return singular if count == 1 else (plural or singular + "s")


class AnalystService:
    """Read-only. Derives facts, then optionally has them narrated."""

    def __init__(self, db: Session, pulse: Optional[MarketPulseService] = None,
                 provider: Optional[AIProvider] = None):
        self.db = db
        self.pulse = pulse or MarketPulseService(db=db)
        # Injectable so tests never reach a real provider.
        self.provider = provider or get_ai_provider()

    # ------------------------------------------------------------------
    def analyse(self, market: Optional[str] = None, location: Optional[str] = None,
                include_summary: bool = True) -> AnalystResponse:
        snapshot = self.pulse.snapshot(market=market, location=location)

        sections = {
            "market_overview": self._market_overview(snapshot),
            "competitor_observations": self._competitors(snapshot),
            "product_observations": self._products(snapshot),
            "price_analysis": self._prices(snapshot),
            "visibility_observations": self._visibility(snapshot),
            "trend_analysis": self._trends(snapshot),
            "data_quality": self._data_quality(snapshot),
        }
        flattened = [o for group in sections.values() for o in group]

        response = AnalystResponse(
            generated_at=datetime.now(timezone.utc),
            context=snapshot.context,
            has_data=snapshot.has_data,
            provider_configured=self.provider.is_configured(),
            provider_name=getattr(self.provider, "name", None),
            observations=flattened,
            evidence=[o.evidence for o in flattened],
            **sections)

        if not snapshot.has_data:
            response.detail = (
                snapshot.detail or
                "No observations match this market and location, so there is "
                "nothing to analyse.")
            return response

        if include_summary and self.provider.is_configured():
            summary, rejected, reason, error = self._summarise(flattened)
            response.summary = summary
            response.summary_rejected = rejected
            response.summary_rejection_reason = reason
            response.provider_error = error
            if summary:
                response.analysis_mode = "assisted"
        elif include_summary:
            response.detail = (
                "No AI provider is configured, so no narrative summary was "
                "produced. The factual analysis below is computed directly "
                "from the Market Pulse snapshot and does not require one.")

        return response

    # ------------------------------------------------------------------
    # Deterministic sections
    # ------------------------------------------------------------------
    @staticmethod
    def _market_overview(snapshot: MarketPulseResponse) -> List[Observation]:
        context = snapshot.context
        out = [Observation(
            section="market_overview", kind=OBSERVATION,
            statement=(
                "The snapshot covers " + (context.market or "all recorded markets")
                + " in " + (context.location or "all recorded locations") + "."),
            evidence=_ref("context", "selected market and location"))]

        if not snapshot.has_data:
            out.append(Observation(
                section="market_overview", kind=INSUFFICIENT,
                statement="No observations have been recorded for this selection.",
                evidence=_ref("context", count=0)))
            return out

        out.append(Observation(
            section="market_overview", kind=OBSERVATION,
            statement=(
                str(context.merchants) + " " + _plural(context.merchants, "merchant")
                + " " + _plural(context.merchants, "is", "are") + " represented, from "
                + str(context.competitor_observations) + " competitor "
                + _plural(context.competitor_observations, "observation") + " and "
                + str(context.product_observations) + " product "
                + _plural(context.product_observations, "observation") + "."),
            evidence=_ref("context", "observation counts", count=context.merchants)))

        if context.first_observed_at and context.last_observed_at:
            span = context.observation_span_hours
            out.append(Observation(
                section="market_overview", kind=OBSERVATION,
                statement=(
                    "Observations span " + str(span) + " hours, from "
                    + context.first_observed_at.strftime("%Y-%m-%d %H:%M")
                    + " to " + context.last_observed_at.strftime("%Y-%m-%d %H:%M")
                    + ", across " + str(context.distinct_searches) + " distinct "
                    + _plural(context.distinct_searches, "search", "searches") + "."),
                evidence=_ref("context", "observation period",
                              count=context.distinct_searches)))
        return out

    @staticmethod
    def _competitors(snapshot: MarketPulseResponse) -> List[Observation]:
        entries = snapshot.competitors
        if not entries:
            return [Observation(
                section="competitor_observations", kind=INSUFFICIENT,
                statement="No businesses have been observed for this selection.",
                evidence=_ref("competitors", count=0))]

        out = []
        for status in ("verified", "discovered", "uncertain"):
            group = [e for e in entries if e.status == status]
            if not group:
                continue
            explanation = {
                "verified": "identified from a structured local listing or "
                            "corroborated by two independent sources",
                "discovered": "identified from a single organic result, which is "
                              "weaker evidence",
                "uncertain": "not identified reliably enough to attribute evidence to",
            }[status]
            out.append(Observation(
                section="competitor_observations", kind=OBSERVATION,
                statement=(
                    str(len(group)) + " " + status + " "
                    + _plural(len(group), "business", "businesses") + " "
                    + _plural(len(group), "was", "were") + " observed ("
                    + explanation + "): " + ", ".join(e.name for e in group) + "."),
                evidence=_ref("competitors", status,
                              merchant_ids=[e.merchant_id for e in group if e.merchant_id],
                              count=len(group))))

        absent = [e for e in entries if not e.present_in_latest]
        if absent:
            out.append(Observation(
                section="competitor_observations", kind=LIMITATION,
                statement=(
                    str(len(absent)) + " " + _plural(len(absent), "business", "businesses")
                    + " " + _plural(len(absent), "was", "were")
                    + " not present in the latest observation of this context: "
                    + ", ".join(e.name for e in absent)
                    + ". Absence from one search is not evidence that a business "
                      "has closed or left the market."),
                evidence=_ref("competitors", "absent from latest observation",
                              merchant_ids=[e.merchant_id for e in absent if e.merchant_id],
                              count=len(absent))))

        return out

    @staticmethod
    def _products(snapshot: MarketPulseResponse) -> List[Observation]:
        entries = snapshot.products
        if not entries:
            return [Observation(
                section="product_observations", kind=INSUFFICIENT,
                statement="No product observations have been recorded for this selection.",
                evidence=_ref("products", count=0))]

        out = []
        for status, wording in (
                ("found", "the merchant's own site identified the product"),
                ("not_found", "a result specifically contradicted the request"),
                ("unknown", "the evidence was insufficient either way, which is "
                            "not a finding that the product is unavailable")):
            group = [e for e in entries if e.product_status == status]
            if not group:
                continue
            out.append(Observation(
                section="product_observations",
                kind=INSUFFICIENT if status == "unknown" else OBSERVATION,
                statement=(
                    str(len(group)) + " product " + _plural(len(group), "observation")
                    + " " + _plural(len(group), "is", "are") + " '"
                    + status.replace("_", " ") + "' (" + wording + ")."),
                evidence=_ref("products", status,
                              record_ids=[e.observation_id for e in group],
                              count=len(group))))

        catalog = [e for e in entries if e.evidence_scope == "catalog"
                   and not e.inventory_confirmed]
        if catalog:
            out.append(Observation(
                section="product_observations", kind=LIMITATION,
                statement=(
                    str(len(catalog)) + " " + _plural(len(catalog), "observation")
                    + " " + _plural(len(catalog), "comes", "come")
                    + " from a merchant catalogue. Catalogue evidence shows the "
                      "merchant offers the product; it does not establish that a "
                      "physical store holds stock."),
                evidence=_ref("products", "catalog scope, inventory not confirmed",
                              record_ids=[e.observation_id for e in catalog],
                              count=len(catalog))))
        return out

    @staticmethod
    def _prices(snapshot: MarketPulseResponse) -> List[Observation]:
        prices = snapshot.prices
        stats = snapshot.price_statistics
        unverified = [p for p in snapshot.products if p.price_status == "unavailable"]

        out: List[Observation] = []
        if not prices:
            out.append(Observation(
                section="price_analysis", kind=INSUFFICIENT,
                statement=(
                    "No verified price measurements are available for this "
                    "selection. Only a price attributable to the exact product on "
                    "a product-specific page is counted."),
                evidence=_ref("prices", count=0)))
        else:
            out.append(Observation(
                section="price_analysis", kind=OBSERVATION,
                statement=(
                    # Observations, not measurements: a repeated cached reading
                    # is stored again, so the distinct count is stated beside it.
                    str(len(prices)) + " verified price "
                    + _plural(len(prices), "observation") + " "
                    + _plural(len(prices), "is", "are") + " recorded ("
                    + str(stats.distinct_measurements) + " distinct "
                    + _plural(stats.distinct_measurements, "measurement") + "): "
                    + "; ".join(
                        (p.merchant or "unknown merchant") + " "
                        + (p.product_name or p.product_query) + " at "
                        + ("%.2f" % p.price) + " " + (p.currency or "")
                        for p in prices).strip() + "."),
                evidence=_ref("prices", "verified price observations",
                              record_ids=[p.observation_id for p in prices],
                              count=len(prices))))

            if stats.sufficient:
                out.append(Observation(
                    section="price_analysis", kind=OBSERVATION,
                    statement=(
                        "Across " + str(stats.distinct_measurements)
                        + " distinct verified measurements the observed prices "
                          "range from " + ("%.2f" % stats.lowest) + " to "
                        + ("%.2f" % stats.highest) + ", averaging "
                        + ("%.2f" % stats.average)
                        + ". These describe what was observed, not a market rate."),
                    evidence=_ref("prices", "price statistics",
                                  count=stats.distinct_measurements)))
            else:
                out.append(Observation(
                    section="price_analysis", kind=INSUFFICIENT,
                    statement=(
                        "There " + _plural(stats.distinct_measurements, "is", "are")
                        + " only " + str(stats.distinct_measurements)
                        + " distinct verified price "
                        + _plural(stats.distinct_measurements, "measurement")
                        + ", which is insufficient to summarise. Repeating a "
                          "search inside the response cache returns the same "
                          "reading and does not add a measurement."),
                    evidence=_ref("prices", "insufficient distinct measurements",
                                  count=stats.distinct_measurements)))

        if unverified:
            out.append(Observation(
                section="price_analysis", kind=LIMITATION,
                statement=(
                    str(len(unverified)) + " product "
                    + _plural(len(unverified), "observation") + " had price "
                      "evidence that could not be verified and "
                    + _plural(len(unverified), "was", "were")
                    + " excluded from price analysis."),
                evidence=_ref("products", "price_status unavailable",
                              record_ids=[p.observation_id for p in unverified],
                              count=len(unverified))))
        return out

    @staticmethod
    def _visibility(snapshot: MarketPulseResponse) -> List[Observation]:
        entries = snapshot.visibility
        if not entries:
            return [Observation(
                section="visibility_observations", kind=INSUFFICIENT,
                statement="No visibility measurements are available for this selection.",
                evidence=_ref("visibility", count=0))]

        out = []
        positioned = [e for e in entries if e.best_position is not None]
        if positioned:
            out.append(Observation(
                section="visibility_observations", kind=OBSERVATION,
                statement=(
                    str(len(positioned)) + " " + _plural(len(positioned), "business", "businesses")
                    + " had a recorded search position: "
                    + "; ".join(e.merchant + " at position " + str(e.best_position)
                                for e in positioned)
                    + ". Position is where a result appeared in one search, not a "
                      "ranking of the businesses."),
                evidence=_ref("visibility", "best recorded position",
                              merchant_ids=[e.merchant_id for e in positioned if e.merchant_id],
                              count=len(positioned))))

        rated = [e for e in entries if e.rating is not None]
        if rated:
            out.append(Observation(
                section="visibility_observations", kind=OBSERVATION,
                statement=(
                    str(len(rated)) + " " + _plural(len(rated), "business", "businesses")
                    + " had a recorded rating: "
                    + "; ".join(
                        e.merchant + " " + str(e.rating)
                        + (" from " + str(e.reviews) + " reviews" if e.reviews is not None else "")
                        for e in rated) + "."),
                evidence=_ref("visibility", "rating and review counts",
                              merchant_ids=[e.merchant_id for e in rated if e.merchant_id],
                              count=len(rated))))

        unrated = [e for e in entries if e.rating is None]
        if unrated:
            out.append(Observation(
                section="visibility_observations", kind=LIMITATION,
                statement=(
                    str(len(unrated)) + " " + _plural(len(unrated), "business", "businesses")
                    + " had no rating recorded by any provider."),
                evidence=_ref("visibility", "no rating reported",
                              merchant_ids=[e.merchant_id for e in unrated if e.merchant_id],
                              count=len(unrated))))
        return out

    @staticmethod
    def _trends(snapshot: MarketPulseResponse) -> List[Observation]:
        """Trend facts come from TrendsService output only.

        Nothing is recalculated here: the direction, the distinct-point count
        and the insufficient-history verdict are all read from the series as
        Market Pulse supplied them.
        """
        series = snapshot.trends
        if not series:
            return [Observation(
                section="trend_analysis", kind=INSUFFICIENT,
                statement="No trend series are available for this selection.",
                evidence=_ref("trends", count=0))]

        out = []
        directional = [s for s in series if s.status == "trend"]
        insufficient = [s for s in series if s.status == "insufficient_history"]

        for s in directional:
            change = ""
            if s.first_value is not None and s.last_value is not None:
                change = (" from " + str(s.first_value) + " to " + str(s.last_value))
            out.append(Observation(
                section="trend_analysis", kind=OBSERVATION,
                statement=(
                    s.subject + ": " + str(s.distinct_points)
                    + " distinct " + _plural(s.distinct_points, "measurement")
                    + " of " + s.metric + " are available, and the observed value "
                    + {"up": "increased", "down": "decreased",
                       "flat": "did not change"}.get(s.direction, "changed")
                    + change + "."),
                evidence=_ref("trends", s.metric + " / " + (s.context or "no context"),
                              count=s.distinct_points)))

        if insufficient:
            out.append(Observation(
                section="trend_analysis", kind=INSUFFICIENT,
                statement=(
                    str(len(insufficient)) + " trend "
                    + _plural(len(insufficient), "series", "series")
                    + " " + _plural(len(insufficient), "holds", "hold")
                    + " a single distinct measurement, which is insufficient to "
                      "determine a trend. A repeated reading served from the "
                      "response cache is the same measurement, not a new one."),
                evidence=_ref("trends", "insufficient history",
                              count=len(insufficient))))
        return out

    @staticmethod
    def _data_quality(snapshot: MarketPulseResponse) -> List[Observation]:
        out: List[Observation] = []

        no_domain = [c for c in snapshot.competitors if not c.domain]
        if no_domain:
            out.append(Observation(
                section="data_quality", kind=LIMITATION,
                statement=(
                    str(len(no_domain)) + " " + _plural(len(no_domain), "business", "businesses")
                    + " had no website domain reported: "
                    + ", ".join(c.name for c in no_domain)
                    + ". A platform page such as a social profile is retained as "
                      "evidence but is not recorded as a business's own domain."),
                evidence=_ref("competitors", "no domain reported",
                              merchant_ids=[c.merchant_id for c in no_domain if c.merchant_id],
                              count=len(no_domain))))

        no_location = [c for c in snapshot.competitors if not c.has_location_evidence]
        if no_location:
            out.append(Observation(
                section="data_quality", kind=LIMITATION,
                statement=(
                    str(len(no_location)) + " " + _plural(len(no_location), "business", "businesses")
                    + " had no address or coordinates reported, so geographic "
                      "relevance to this location could not be verified: "
                    + ", ".join(c.name for c in no_location)
                    + ". Nothing is inferred from the domain name."),
                evidence=_ref("competitors", "no location evidence",
                              merchant_ids=[c.merchant_id for c in no_location if c.merchant_id],
                              count=len(no_location))))

        for note in snapshot.data_quality.notes:
            out.append(Observation(
                section="data_quality", kind=LIMITATION, statement=note,
                evidence=_ref("data_quality", "reported by Market Pulse")))

        if not out:
            out.append(Observation(
                section="data_quality", kind=OBSERVATION,
                statement="No data-quality limitations were recorded for this selection.",
                evidence=_ref("data_quality", count=0)))
        return out

    # ------------------------------------------------------------------
    # Narrative summary
    # ------------------------------------------------------------------
    def _summarise(self, observations: List[Observation]
                   ) -> Tuple[Optional[str], bool, Optional[str], Optional[str]]:
        """Ask the provider to narrate the computed facts, then validate it.

        Returns (summary, rejected, rejection_reason, provider_error).
        """
        facts = [o.statement for o in observations]
        user_prompt = ("Statements computed from recorded observations:\n"
                       + "\n".join("- " + f for f in facts))

        try:
            raw = self.provider.generate(SYSTEM_PROMPT, user_prompt)
        except AIProviderNotConfigured as exc:
            return None, False, None, str(exc)
        except AIProviderError as exc:
            return None, False, None, str(exc)
        except Exception as exc:
            # A provider fault must not take the factual analysis down with it.
            return None, False, None, (
                "The AI provider failed: " + type(exc).__name__ + ".")

        summary = (raw or "").strip()
        if not summary:
            return None, False, None, "The AI provider returned an empty summary."

        ok, reason = validate_summary(summary, facts)
        if not ok:
            return None, True, reason, None
        return summary, False, None, None


def _canonical_number(text: str) -> str:
    """"19.90" and "19.9" are the same figure; "019" is "19"."""
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text.lstrip("0") or "0"


def validate_summary(summary: str, facts: List[str]) -> Tuple[bool, Optional[str]]:
    """Reject a narrative that asserts more than the facts support.

    Two checks, both blunt on purpose -- a withheld summary costs a
    convenience, an unfounded one costs the credibility of everything else:

    1. No banned conclusion may appear.
    2. Every number in the prose must appear somewhere in the computed facts,
       so a figure cannot be introduced, rounded or recombined.
    """
    for claim, pattern in _BANNED_PATTERNS:
        if pattern.search(summary):
            return False, ("The summary asserted a conclusion the evidence does "
                           "not support: '" + claim + "'.")

    known = set()
    for fact in facts:
        known.update(_canonical_number(n) for n in _NUMBER_RE.findall(fact))

    # Exact membership only. A prefix test here once accepted any figure that
    # began with a known one -- and with 0, 1 and 2 always "known", that let
    # "250 stores" or "1000 dollars" through. "19.99" restated as "19.9" or
    # "20" is a different figure and is rejected.
    for number in _NUMBER_RE.findall(summary):
        if _canonical_number(number) in known:
            continue
        return False, ("The summary cited a figure that does not appear in the "
                       "computed facts: '" + number + "'.")
    return True, None
